# Generated by Django 4.2.11 on 2024-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideosModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("userImage", models.ImageField(upload_to="userImage/")),
                ("video", models.FileField(upload_to="videos/")),
            ],
        ),
    ]
